# =============================================================================
# GTK 4 settings
# =============================================================================

[Settings]

gtk-theme-name=Adwaita
gtk-application-prefer-dark-theme=1

gtk-icon-theme-name=Adwaita

gtk-font-name=Ubuntu Bold 13

gtk-cursor-theme-name=Adwaita
gtk-cursor-theme-size=24

gtk-enable-animations=1